version: '3'

services:
  db:
    image: postgres:14.13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: raw_recommendation
      POSTGRES_USER: prafulnepal
      POSTGRES_PASSWORD: Midaseducation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql

  redis:
    image: redislabs/rebloom:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  tor-proxy:
    image: dperson/torproxy
    container_name: tor-proxy
    restart: always
    ports:
      - "9050:9050"  # SOCKS proxy port
      - "9051:9051"  # Control port (optional)
    environment:
      TOR_EXTRA_OPTS: "-socksport 9050 -controlport 9051 -AutomapHostsOnResolve 1"

  app:
    build: .
    container_name: prediction-app
    depends_on:
      - db
      - redis
      - tor-proxy  # Ensure Tor starts first
    environment:
      DB_HOST: db
      DB_NAME: raw_recommendation
      DB_USER: prafulnepal
      DB_PASSWORD: Midaseducation
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TOR_PROXY: "socks5h://tor-proxy:9050"  # Use the service name `tor-proxy`
    ports:
      - "5000:5000"
    volumes:
      - ./tor_logs:/var/log/tor  # Optional: Persist Tor logs

volumes:
  postgres_data:
